### ISSUE TITLE
docker run -d nginx fails

### ISSUE THREAD

**Issue by h0lzi** [joyent/sdc-docker#1]
Might be more of an Platform Image problem but thought would raise it here:

docker run -d nginx
Unable to find image 'nginx:latest' locally
....

Status: Downloaded newer image for library/nginx:latest
ef6ab9a1aabf44bb9f1ce3a85c1f3feff3eeb2bb824a4fe7b1530194721cb504
FATA[0067] Error response from daemon: InternalError: Problem starting container: {"message":"VM.start error: Command failed: could not verify fs /var/cache/nginx: could not access zones/ef6ab9a1-aabf-44bb-9f1c-e3a85c1f3fef/volumes/95966fa7-9c3a-48c1-b4a2-f405d1060083: No such file or directory\nzoneadm: zone ef6ab9a1-aabf-44bb-9f1c-e3a85c1f3fef failed to verify\n"} 

it's a coal install so checked headnode and zone is not booted:
- ef6ab9a1-aabf-44bb-9f1c-e3a85c1f3fef installed  /zones/ef6ab9a1-aabf-44bb-9f1c-e3a85c1f3fef lx       excl 

[root@headnode (bo) ~]# zoneadm -z ef6ab9a1-aabf-44bb-9f1c-e3a85c1f3fef boot
could not verify fs /var/cache/nginx: could not access zones/ef6ab9a1-aabf-44bb-9f1c-e3a85c1f3fef/volumes/95966fa7-9c3a-48c1-b4a2-f405d1060083: No such file or directory
zoneadm: zone ef6ab9a1-aabf-44bb-9f1c-e3a85c1f3fef failed to verify

busybox image does fail too:
docker run -d busybox      
f41d53805c294efcb10d289b7374816912771637e5b746ccb3c73d8eb9fe9e87

docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

- f41d5380-5c29-4efc-b10d-289b73748169 installed  /zones/f41d5380-5c29-4efc-b10d-289b73748169 lx       excl 

not sure if that is supposed to work anyway:
[root@headnode (bo) ~]# zoneadm -z f41d5380-5c29-4efc-b10d-289b73748169 boot
[root@headnode (bo) ~]# 
but does not boot either

**Comment by rmustacc** [comment]
Hi, could you include the version of the platform you're running (uname -v) and the version of the various SDC components?

**Comment by h0lzi** [comment]
sure:
joyent_20150205T055835Z

updated alle Services today:

SERVICE VERSION
adminui master-20150211T193615Z-g105bd5c
amon master-20150211T191508Z-g58ecaf8
amonredis master-20150211T192850Z-g4bbca77
assets master-20150211T192901Z-g6012d50
binder master-20150211T193321Z-gba090a8
ca master-20150211T194304Z-gb775d2d
cloudapi master-20150212T141718Z-gadbe018
cnapi master-20150211T194049Z-gc70a578
dhcpd master-20150211T194011Z-g938f87a
docker master-20150213T013603Z-g710a090
fwapi master-20150211T193801Z-g7b51ccd
hostvolume master-20150211T091713Z-g20cd789
imgapi master-20150211T191905Z-gf7c1e24
mahi master-20150211T193306Z-gd15eaf4
manatee master-20150211T191839Z-gcd788b8
moray master-20150211T193848Z-g97aa5cc
napi master-20150211T192504Z-gc6be61d
papi master-20150211T193953Z-g7905a77
rabbitmq release-20150205-20150205T074202Z-g3bf8269
redis master-20150211T192256Z-g0d6e5b9
sapi master-20150212T050846Z-g14fa2e4
sdc master-20150211T202435Z-ga26135d
ufds master-20150211T192938Z-gbd2a8fa
vmapi master-20150211T193143Z-ga703987
workflow master-20150211T192757Z-gc1de0cf

**Comment by rmustacc** [comment]
There are known issues with that version of the platform for docker; however, I haven't personally seen them cause the failure mode that you've hit. Most likely, updating your platform would be the next step here, though we may need to come back and ask for more information to better understand the failure that you hit.

**Comment by h0lzi** [comment]
Well will wait for the next platform and update. This is the firsttime the hostvolume is deployed before that it was nfs something. That created a /manta in the global. 
Will close this for now and wait for new image

**Comment by rmustacc** [comment]
You can manually update to the latest platform and not wait for the release, fwiw.

**Comment by h0lzi** [comment]
ok did nginx now works. thanks

**Comment by rmustacc** [comment]
Okay, great!
