### ISSUE TITLE
/var/run/docker.sock alternative ?

### ISSUE THREAD

**Issue by lucj** [joyent/sdc-docker#115]
Several Docker images rely on the host's /var/run/docker.sock socket to get events from the docker host and start/stop containers. As this socket is not available when running Docker containers on Triton, what is the recommended way to do it ?
My use case is the setup of a CI/CD pipeline, especially the CD part, where a service could regularly check new version of an image (available on the DockerHub) and update the running services based on this image.

**Comment by jclulow** [comment]
I think it makes sense to generate key material inside the container that needs access to the Docker API, add it to the appropriate Triton account(s), and have the software make regular HTTPS API calls to the Triton data centre(s) to which it needs to communicate.

**Comment by tgross** [comment]
@lucj for my team's [Jenkins environment](https://github.com/autopilotpattern/jenkins) we do just as @jclulow is suggesting. See https://github.com/autopilotpattern/mysql/blob/master/makefile for an example of what the job itself might look like.

**Comment by lucj** [comment]
@jclulow @tgross thanks a lot, really interesting approach, I'll check this carrefully.

**Comment by cheapRoc** [comment]
@lucj How do we feel about closing this issue?

**Comment by lucj** [comment]
Sorry, I should have closed it earlier.
Thanks for your help.

**Comment by cheapRoc** [comment]
@lucj No problem at all, thanks.
