### ISSUE TITLE
Failed CloudAPI access with windows docker client under Cygwin

### ISSUE THREAD

**Issue by arnos** [joyent/sdc-docker#26]
I was testing the new docker client under windows  with the sdc-docker-setup.sh script and I ran into an error when veryfying the CloudAPI access.

```
sdc-docker-setup.sh: fatal error: invalid credentials
    You must add create the 'a***@***.com' account and/or add your SSH
    public key (/home/a***/.ssh/id_rsa.pub) to the
    given SmartDataCenter.
```

**Comment by arnos** [comment]
This was inside of Cygwin, but adding the setup support for windows (CMD, PS) would also solve this issue.

**Comment by lloydde** [comment]
@arnos did you recently install or update cygwin? It looks like OpenSSH_6.8p1 changes the output of `ssh-keygen -l`. Go back to OpenSSH_6.7p1 and you should be able to run the sdc-docker-setup.sh successfully.

(I haven't yet used docker itself on mswin.)

**Comment by lloydde** [comment]
@arnos this part of the issue is now fixed with https://smartos.org/bugview/DOCKER-324 .

**Comment by lloydde** [comment]
Confirmed that after copying files generated by sdc-docker-setup.sh from .sdc\docker to %USERPROFILE%\.docker that `docker --tls -H tcp://us-east-3b.docker.joyent.com:2376 ps` worked as expected.

**Comment by arnos** [comment]
I will test it tomorrow or Friday

thanks

**Comment by arnos** [comment]
ok it works with SDC

**Comment by lloydde** [comment]
Thanks @arnos !
