### ISSUE TITLE
Target machine refused connection

### ISSUE THREAD

**Issue by arnos** [joyent/sdc-docker#28]
$ docker ps
time="2015-05-04T14:58:20-04:00" level=fatal msg="An error occurred trying to connect: Get https://us-east-3b.docker.joyent.com:2376/v1.18/containers/json: dial tcp 165.225.168.25:2376: ConnectEx tcp: No connection could be made because the target machine actively refused it."

**Comment by rmustacc** [comment]
@arnos it looks like you're actively using the Joyent Public Cloud. You should file support tickets by e-mailing support@joyent.com or going to https://help.joyent.com/.

**Comment by arnos** [comment]
Sorry wrong copy and paste yes I was testing against a self-hosted SDC and Joyent to see if I could reproduce the error.
