### ISSUE TITLE
"file a ticket"

### ISSUE THREAD

**Issue by lloydde** [joyent/sdc-docker#34]
"Please contact Joyent support or file a ticket if you discover any additional differences." has been added to every command page.

1. "file a ticket" isn't a phrase we currently use. Do you mean "support ticket"? 

2. At a higher level, maybe this could be inserted on publish, so the documentation can also stand on its own.

/cc @qdzlug

**Comment by misterbisson** [comment]
[File an issue/ticket/complate](https://github.com/joyent/sdc-docker/issues/new)
