### ISSUE TITLE
docker services crashes.

### ISSUE THREAD

**Issue by h0lzi** [joyent/sdc-docker#4]
joyent_20150219T091122Z

docker master-20150224T013553Z-g8bcc8c6

normal docker ps kills service:

```
[2015-02-24T15:19:57.400Z]  INFO: docker/16525 on 813d0f8e-939b-4ab9-9278-6349f646a97c:  (req_id=97819580-bc38-11e4-8cf4-49ada73feedb)
    evt: {
      "ph": "b",
      "name": "containerlist"
    }
Uncaught AssertionError: params.image_uuid (string) is required

FROM
_assert (/opt/smartdc/docker/node_modules/assert-plus/assert.js:45:31)
Object.string (/opt/smartdc/docker/node_modules/assert-plus/assert.js:160:9)
new Image (/opt/smartdc/docker/lib/models/image.js:55:12)
EventEmitter._onListRec (/opt/smartdc/docker/lib/moray.js:256:53)
EventEmitter.emit (events.js:95:17)
EventEmitter.onObject (/opt/smartdc/docker/node_modules/moray/lib/objects.js:190:13)
EventEmitter.emit (events.js:95:17)
Client._handleMessage (/opt/smartdc/docker/node_modules/moray/node_modules/fast/lib/client.js:365:22)
MessageDecoder.onMessage (/opt/smartdc/docker/node_modules/moray/node_modules/fast/lib/client.js:446:14)
MessageDecoder.emit (events.js:95:17)
MessageDecoder._write (/opt/smartdc/docker/node_modules/moray/node_modules/fast/lib/protocol/message_decoder.js:121:14)
doWrite (/opt/smartdc/docker/node_modules/moray/node_modules/fast/node_modules/readable-stream/lib/_stream_writable.js:263:12)
writeOrBuffer (/opt/smartdc/docker/node_modules/moray/node_modules/fast/node_modules/readable-stream/lib/_stream_writable.js:250:5)
MessageDecoder.Writable.write (/opt/smartdc/docker/node_modules/moray/node_modules/fast/node_modules/readable-stream/lib/_stream_writable.js:197:11)
write (_stream_readable.js:601:24)
flow (_stream_readable.js:610:7)
Socket.pipeOnReadable (_stream_readable.js:642:5)
Socket.emit (events.js:92:17)
emitReadable_ (_stream_readable.js:426:10)
emitReadable (_stream_readable.js:422:5)
readableAddChunk (_stream_readable.js:165:9)
Socket.Readable.push (_stream_readable.js:127:10)
TCP.onread (net.js:528:21)
[ Feb 24 15:19:57 Stopping because all processes in service exited. ]
[ Feb 24 15:19:57 Executing stop method (:kill). ]
[ Feb 24 15:19:57 Executing start method ("/opt/smartdc/docker/smf/method/docker start"). ]
```

**Comment by cachafla** [comment]
Hi, it seems you have a recent docker zone but you might have outdated workflow or imgapi zones. Can you run these 3 commands to ensure you have the latest bits and then try again:
```
sdcadm self-update
sdcadm update imgapi
sdcadm update workflow
sdcadm experimental update-docker
```

**Comment by cachafla** [comment]
Also this:

```
sdcadm experimental update-agents --latest
```

**Comment by misterbisson** [comment]
@cachafla, is that preferred over `sdcadm update --all -y` in this context, or are they complementary? Should I update the bottom of https://www.joyent.com/blog/test-drive-joyents-elastic-container-infrastructure-for-docker ?

**Comment by trentm** [comment]
@misterbisson Not in general, but @cachafla is responding to a specific recent flag day where we know only those components *need* to be updated.  Updating everything should also be fine (modulo other bugs), but will take longer.

**Comment by h0lzi** [comment]
Normally I do a update --all in the morning :) Will check again later today

**Comment by h0lzi** [comment]
ok up and freash:
joyent_20150225T020339Z

docker           headnode  master-20150225T033235Z-g1d08736
imgapi           headnode  master-20150225T033952Z-g3331fae 
workflow         headnode  master-20150225T052208Z-g2a160f5 


still the same:

docker ps
FATA[0000] Get http://10.88.88.7:2375/v1.17/containers/json: EOF. Are you trying to connect to a TLS-enabled daemon without TLS? 
[1]    18881 exit 1     docker ps

[2015-02-25T10:55:50.198Z]  INFO: docker/17728 on 813d0f8e-939b-4ab9-9278-6349f646a97c:  (req_id=dc400e50-bcdc-11e4-a565-3f29a40fdd38)
    evt: {
      "ph": "b",
      "name": "containerlist"
    }
Uncaught AssertionError: params.image_uuid (string) is required

FROM
_assert (/opt/smartdc/docker/node_modules/assert-plus/assert.js:45:31)

**Comment by cachafla** [comment]
I think I know what's going on your install. What is the image this container belongs to? I think the image as it exists in the database is missing new fields that were added last week. What we can do to fix this is to re-pull the image completely (your container is not going to go away).

So, assuming your image is 'busybox', you have to run the following two commands:

```
docker rmi busybox
docker pull busybox
```

`docker ps` should work after that.

**Comment by h0lzi** [comment]
well removed all docker-layer images. didn't help.
Will reinstall the whole coal tomorrow. Maybe I'm in a deadlock there somehow

**Comment by cachafla** [comment]
You can also try this as a last-resort:

```
sdc-login moray
delbucket docker_images
delbucket docker_image_tags
exit

sdc-login docker
svcadm restart docker
```
That will cause a full reset of the images bucket so you will have to re-pull every image you had before, but this will most likely fix your issue.

**Comment by h0lzi** [comment]
to late.
Did reinstall today. Back to normal. More or less. But will create new ticket for that
