### ISSUE TITLE
docker pull fails

### ISSUE THREAD

**Issue by bixu** [joyent/sdc-docker#5]
Following the recent blog post, I'm getting this:
```
irvin › docker run --rm busybox echo "Hello."
Unable to find image 'busybox:latest' locally

FATA[0121] Post http://10.88.88.6:2375/v1.17/images/create?fromImage=busybox&tag=latest: EOF
```

**Comment by misterbisson** [comment]
I had similar problems when I was on a dodgy network yesterday (same as with the `sdcadm experimental update-docker` problem discussed in the mail list). 

I assume you've tried explicit pulls and those are failing repeatedly?

**Comment by bastichelaar** [comment]
I'm encountering the same problem. My internet connection is not very fast, but it's stable. I also don't see any images getting pulled.

**Comment by bastichelaar** [comment]
It seems fixed when using the following commands:
```
sdcadm self-update
sdcadm update imgapi
sdcadm update workflow
sdcadm experimental update-docker
```

**Comment by lloydde** [comment]
Good news @bastichelaar.

@bixu where you able to get past this with an update like @bastichelaar ?

**Comment by bixu** [comment]
I did something like
```
sdcadm self-update
sdcadm update --all -y
sdcadm experimental update-docker
```
and that fixed the issues
