### ISSUE TITLE
Divergence on `docker cp`

### ISSUE THREAD

**Issue by cehoffman** [joyent/sdc-docker#59]
Where files are placed locally when using `docker cp` differs between official docker and sdc-docker. Here is a table showing where the copied file is placed.

| Command | Official Docker | SDC Docker |
| --- | --- | --- |
| docker cp container:/etc/nginx/nginx.conf .` | nginx.conf | etc/nginx/nginx.conf |
| docker cp container:/etc/nginx/nginx.conf default.conf` | default.conf | etc/nginx/default.conf |

It appears that SDC Docker includes full directory information when passing the file contents back to the client docker.

**Comment by orlandov** [comment]
Hi Chris! I just reproduced this, thanks for the heads up. I'll look into this and get a fix out ASAP.
