### ISSUE TITLE
'docker network' is not supported

### ISSUE THREAD

**Issue by dissipate** [joyent/sdc-docker#67]
Looks like the [docker network](https://docs.docker.com/engine/userguide/networking/work-with-networks/) command is not supported. I wouldn't care or notice this so much except for the fact that docker-compose version 2 tries to create a default network, and hence, is not compatible with sdc-docker.

**Comment by notmatt** [comment]
@dissipate - I'm actively working on this now that docker networking seems to have stabilized. There are several internal tickets below, though not a lot of details at this point; we have to sort out some of the precise behaviour first, there will be an RFD shortly. While the devil is (as always) in the details, `docker network` maps fairly closely to our existing fabric support, and I don't anticipate large problems in implementation.

Tickets:

  - [`docker run --net=`](https://smartos.org/bugview/DOCKER-585) (some older discussion there)
  - [`docker network create`](https://smartos.org/bugview/DOCKER-723)
  - [`docker network attach`](https://smartos.org/bugview/DOCKER-724)
  - [`docker network ls`](https://smartos.org/bugview/DOCKER-725)
  - [`docker network inspect`](https://smartos.org/bugview/DOCKER-726)

I'm going to close this issue in preference to the above, but if there's anything you think might be missing, please do add it here; I'll also update this when the RFD goes out. Thanks!
